rules:
  branches:
    master:
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
        required_status_checks:
          strict: true
          contexts:
            - continuous-integration/travis-ci
        restrictions:
          users:
           - dependabot[bot]
