language: rust
sudo: false
rust: nightly
INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
  |
    rustup target add wasm32-unknown-unknown
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install v11.6
INSTALL_RUST_LINTS: &INSTALL_RUST_LINTS
  |
    rustup component add rustfmt --toolchain nightly || true
    rustup component add clippy --toolchain=nightly \
      || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy \
      || true
cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $HOME/.cache/yarn
  - node_modules
  - common/node_modules
  - backend/node_modules
  - backend/.cache
  - backend/dist
  - frontend/node_modules
  - frontend/.cache
  - frontend/dist
  - rust_common/target
install:
- *INSTALL_NODE_VIA_NVM
- *INSTALL_RUST_LINTS
- cargo install --git https://github.com/mvlabat/wasm-bindgen.git --branch default-support wasm-bindgen-cli --force
- cd common && yarn install
- cd ../backend && yarn install
- cd ../frontend && yarn install
- cd .. && yarn install
- cd rust_common
- if cargo fmt --version; then cargo fmt --all -- --check; else true; fi
- if cargo clippy --version; then cargo clippy; else true; fi
script:
- cd common
- yarn test --verbose
- cd ../backend
- yarn build
- yarn test --verbose
- cd ../frontend
- yarn build
- yarn test --verbose
- cd ..
- yarn eslint
