language: rust
sudo: false
rust: nightly
INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
  |
    rustup target add wasm32-unknown-unknown
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install v11.6
cache:
  yarn: true
  directories:
  - node_modules
  - common/node_modules
  - backend/node_modules
  - backend/.cache
  - backend/dist
  - frontend/node_modules
  - frontend/.cache
  - frontend/dist
install:
- *INSTALL_NODE_VIA_NVM
- cargo install wasm-pack
- cd common && yarn install
- cd ../backend && yarn install
- cd ../frontend && yarn install
- cd .. && yarn install
script:
- cd common
- yarn test --verbose
- cd ../backend
- yarn build
- yarn test --verbose
- cd ../frontend
- yarn build
- yarn test --verbose
- cd ..
- yarn eslint
